let imageUrls = [
    'yoriichi.jpg', 'gyu.jpg', 'shinobu.jpg', 'kyojuro.jpg',
    'mitsuri.jpg', 'obanai.jpg', 'sanemi.jpg', 'gyomei.jpg',
    'muichiro.jpg', 'muichiro.jpg'
];
window.onload = function() {
    preloadImages(imageUrls);
};

function preloadImages(urls) {
    for (var i = 0; i < urls.length; i++) {
        var img = new Image();
        img.src = "../../dist/assets/personagens-background/" + urls[i];
    }
}

const getPersonagem = document.querySelectorAll('.personagens__nav__lista__item')
const selecionarNome = document.querySelector('.selecionado__dados__name')
const respiracao = document.getElementById('Respiracao')
const categoria = document.getElementById('Categoria')

const personagemHistoria = document.querySelector('.historia__texto')
const personagemTitulo = document.querySelector('.historia__titulo--personagem')

const personagensNomes = [
    {tanjiro: 'Tanjiro Kamado', respiracao: 'Sol e Água',
        historia: 'Tanjiro Kamado é o protagonista central de Demon Slayer. Sua jornada começa quando sua família é brutalmente atacada por um demônio, deixando apenas ele e sua irmã, Nezuko, sobreviventes. Determinado a salvar Nezuko e vingar a morte de sua família, Tanjiro se junta aos Caçadores de Demônios. Ele é treinado na Respiração da Água, uma técnica de espada poderosa. Ao longo da série, Tanjiro enfrenta numerosos desafios e batalhas difíceis. Ele forma laços estreitos com seus companheiros de equipe e desenvolve uma profunda empatia pelos outros. Sua determinação em proteger Nezuko e derrotar os demônios o impulsiona a superar suas próprias limitações e se tornar um guerreiro poderoso. No entanto, Tanjiro também carrega uma dor profunda devido às tragédias que testemunhou. Sua jornada é uma busca constante por justiça e redenção, e sua coragem e compaixão o tornam uma figura inspiradora e admirada por todos ao seu redor. Tanjiro personifica os valores de sacrifício, coragem e amizade, tornando-se um símbolo de esperança na luta contra o mal.'},
    {nezuko: 'Nezuko Kamado', tipo: 'Humana/Oni',
        historia: 'Nezuko Kamado é uma personagem central em Demon Slayer. Ela é a irmã mais nova de Tanjiro Kamado, o protagonista da série. A história de Nezuko começa quando sua família é brutalmente atacada por um demônio, deixando-a como a única sobrevivente junto com seu irmão mais velho, Tanjiro. No entanto, Nezuko é transformada em um demônio durante o ataque. Apesar de sua transformação, Nezuko retém parte de sua humanidade e, apesar dos instintos demoníacos, ela não ataca seres humanos. Tanjiro, determinado a salvar sua irmã, se torna um Caçador de Demônios para encontrar uma maneira de curá-la e restaurá-la à sua forma humana. Ao longo da série, Nezuko mostra sua força e determinação, ajudando Tanjiro em suas batalhas contra demônios e protegendo aqueles que ama. Ela desenvolve habilidades especiais únicas devido à sua transformação, como a capacidade de se regenerar rapidamente e liberar poderosos ataques de energia. A jornada de Nezuko é marcada por sua determinação em permanecer fiel à sua humanidade, mesmo após se tornar um demônio. Sua relação próxima com Tanjiro é um dos principais aspectos emocionais da série, e sua determinação em proteger sua família e amigos é uma força motriz ao longo da história.'},
    {zenitsu: 'Zenitsu Agatsuma', respiracao: 'Trovão',
        historia: 'Zenitsu é um dos amigos e companheiros de Tanjiro Kamado na jornada como Caçadores de Demônios. A história de Zenitsu começa quando ele é apresentado como um jovem covarde e medroso que se junta aos Caçadores de Demônios principalmente por desespero e falta de opções. Zenitsu é treinado pelo Mestre Jigoro Kuwajima e, apesar de sua personalidade assustada, ele tem habilidades incríveis quando entra em um estado de inconsciência chamado A Técnica do Trovão e da Lua (ou Estilo do Trovão e da Lua). Nesse estado, Zenitsu se torna extremamente poderoso, mas ele não tem controle sobre suas ações e geralmente não se lembra do que aconteceu depois que ele volta ao normal. Ao longo da série, Zenitsu passa por um desenvolvimento significativo, superando seus medos e inseguranças para se tornar um guerreiro mais confiante e corajoso. Sua determinação em proteger seus amigos, especialmente Nezuko e Tanjiro, o impulsiona a enfrentar desafios cada vez maiores. A história de Zenitsu é marcada por momentos de comédia, drama e ação, e sua jornada de autodescoberta o torna um personagem querido pelos fãs. Sua lealdade aos seus amigos e sua busca por se tornar um verdadeiro herói são aspectos centrais de sua narrativa ao longo da série.'},
    {inosuke: 'Inosuke Hashibira', respiracao: 'Fera',
        historia: 'Inosuke Hashibira é apresentado como um guerreiro selvagem e impulsivo, que vive na montanha e luta contra demônios desde jovem. Inosuke usa uma máscara de javali o tempo todo e é extremamente confiante em suas habilidades de combate. Sua história começa quando ele conhece Tanjiro Kamado e Zenitsu Agatsuma durante uma missão de caça aos demônios. Inosuke, inicialmente, os vê como rivais, mas eventualmente forma uma equipe com eles. Ele é treinado por Tanjiro para aprimorar suas habilidades de combate e trabalhar em equipe. Apesar de sua personalidade rude e temperamental, Inosuke desenvolve um vínculo forte com seus companheiros de equipe e se torna um aliado leal. Sua determinação em se tornar mais forte e proteger aqueles que ama o impulsiona a enfrentar desafios cada vez maiores. Ao longo da série, Inosuke mostra um incrível crescimento pessoal, aprendendo a confiar nos outros e a trabalhar em conjunto para alcançar objetivos comuns. Sua coragem e ferocidade durante as batalhas o tornam uma peça fundamental na luta contra os demônios, e sua jornada de autodescoberta o transforma em um personagem querido pelos fãs.'
    },
    {kanao: 'Kanao Tsuyuri', respiracao: 'Flores',
        historia: 'Kanao Tsuyuri é introduzida como uma garota quieta e reservada que foi vendida como escrava, até ser resgatada pelo Caçador de Demônios Shinobu Kocho. Kanao é treinada por Shinobu para se tornar uma espadachim habilidosa e é ensinada a lutar usando a Respiração do Inseto. A história de Kanao é marcada por sua determinação em superar seu passado doloroso e encontrar sua própria voz. Ela inicialmente tem dificuldade em expressar suas emoções e tomar decisões por conta própria, devido à sua história como escrava. No entanto, ao longo da série, ela gradualmente se torna mais confiante e independente. Kanao desenvolve uma conexão especial com Tanjiro Kamado, o protagonista, e seus amigos, tornando-se uma aliada valiosa na luta contra os demônios. Sua habilidade de combate excepcional e sua natureza compassiva a tornam uma presença reconfortante para aqueles ao seu redor. Ao longo de sua jornada, Kanao busca não apenas se tornar mais forte como espadachim, mas também encontrar um propósito maior em sua vida. Sua história é uma representação poderosa de resiliência e superação, e sua evolução como personagem a torna uma parte essencial do grupo de Caçadores de Demônios.'
    },
    {yoriichi:'Yoriichi Tsugikuni', respiracao: 'Sol',
        historia: 'Yoriichi Tsugikuni é reconhecido como o espadachim mais poderoso da história e o criador original da Respiração do Sol, uma técnica de espada que é a base para muitas das técnicas usadas pelos Caçadores de Demônios. A história de Yoriichi começa quando ele era jovem, e seu irmão mais novo, Michikatsu Tsugikuni, se transforma em um demônio. Determinado a proteger os outros, Yoriichi enfrenta seu irmão em uma batalha épica, demonstrando sua habilidade excepcional com a espada e sua determinação inabalável. Eventualmente, Yoriichi é responsável por derrotar seu irmão e salvar a humanidade do terror dos demônios. Após essa batalha, Yoriichi se retira para viver uma vida tranquila e solitária, deixando para trás um legado de coragem e sacrifício. Sua influência continua a ser sentida ao longo dos séculos, inspirando gerações de Caçadores de Demônios a seguir seus passos e lutar pela justiça. Yoriichi é reverenciado como um herói e uma fonte de inspiração para todos aqueles que seguem o caminho da espada contra as forças '
    },
    {gyu: 'Giyu Tomioka', respiracao:'Água',
        historia: 'Giyu Tomioka é introduzido como um Caçador de Demônios experiente e habilidoso, conhecido por sua calma e determinação em batalha. A história de Giyu começa quando ele encontra Tanjiro Kamado após a tragédia que devastou a família deste último. Giyu se torna o mentor de Tanjiro, guiando-o no caminho para se tornar um Caçador de Demônios. Ao longo da série, Giyu é retratado como um indivíduo solitário e reservado, cujo passado e motivações são envoltos em mistério. No entanto, ele demonstra uma lealdade inabalável aos seus colegas Caçadores de Demônios e uma determinação inabalável em derrotar os demônios que ameaçam a paz. Giyu é habilidoso na Respiração da Água e é capaz de executar técnicas poderosas com sua espada. Sua presença tranquila e confiante inspira confiança em seus aliados e temor em seus inimigos. Ao longo da série, Giyu enfrenta numerosos desafios e sacrifícios pessoais em sua missão para proteger a humanidade dos demônios. Sua história é uma representação de coragem, honra e dedicação ao dever, tornando-o um dos personagens mais respeitados e admirados na série.'
    },
    {shinobu: 'Shinobu Kochō', respiracao: 'Inseto',
        historia: 'Shinobu Kochō é uma Caçadora de Demônios renomada e membro do Corpo de Caçadores de Demônios da respiração dos insetos. Shinobu é conhecida por sua natureza gentil e seu sorriso cativante, que muitas vezes esconde sua determinação feroz em combate. Sua história começa quando ela era jovem, e sua irmã mais nova, Kanae, é morta por um demônio. Determinada a vingar a morte de sua irmã e proteger os inocentes, Shinobu se dedica a se tornar uma Caçadora de Demônios habilidosa. Ela desenvolve habilidades únicas de luta, incluindo o uso de venenos letais, que ela usa para enfraquecer e derrotar seus inimigos. Ao longo da série, Shinobu se torna uma figura respeitada entre os Caçadores de Demônios, conhecida por sua compaixão e sua habilidade em lidar com situações difíceis. Ela forma laços estreitos com seus colegas de equipe e se torna uma mentora e figura de apoio para os mais jovens. No entanto, por trás de sua fachada alegre, Shinobu carrega uma dor profunda pela perda de sua irmã e uma determinação inabalável em erradicar os demônios que causam sofrimento. Sua história é uma mistura de tragédia e esperança, e sua coragem e sacrifício a tornam uma personagem memorável na série.'
    },
    {kyojuro: 'Kyōjurō Rengoku', respiracao: 'Fogo',
        historia: 'Kyōjurō é introduzido como um dos Caçadores de Demônios mais poderosos e respeitados, conhecido por sua incrível habilidade de combate e sua devoção ao dever. A história de Kyōjurō começa quando ele era jovem e testemunhou uma tragédia envolvendo demônios que o inspirou a se tornar um Caçador de Demônios. Ele treinou arduamente para dominar a Respiração do Fogo, uma técnica de espada poderosa e rara. Kyōjurō é retratado como um indivíduo caloroso e enérgico, sempre pronto para ajudar os outros e defender os inocentes. Sua presença imponente e seu espírito destemido o tornam uma figura admirada por seus colegas Caçadores de Demônios e temida por seus inimigos. Ao longo da série, Kyōjurō enfrenta numerosos desafios e batalhas difíceis, demonstrando sua coragem e determinação inabaláveis. Ele se torna um mentor e uma fonte de inspiração para Tanjiro Kamado e outros jovens Caçadores de Demônios, ensinando-lhes lições valiosas sobre honra, dever e trabalho em equipe. No entanto, a história de Kyōjurō é marcada por um trágico destino quando ele sacrifica sua vida em uma batalha épica contra um demônio poderoso, protegendo aqueles que jurou defender até o fim. Sua morte deixa um impacto duradouro nos personagens e nos fãs da série, e seu legado como um verdadeiro herói é lembrado com reverência e admiração.'
    },
    {mitsuri: 'Mitsuri Kanroji', respiracao: 'Amor',
        historia: 'Mitsuri Kanroji  é introduzida como uma Caçadora de Demônios talentosa e poderosa, conhecida por sua personalidade alegre e otimista. A história de Mitsuri começa quando ela era jovem e descobre suas habilidades excepcionais como espadachim. Determinada a usar seus dons para proteger os outros, Mitsuri se junta ao Corpo de Caçadores de Demônios e se dedica a combater os demônios que ameaçam a paz. Ela é treinada na Respiração do Amor, uma técnica de espada única que reflete sua natureza gentil e compassiva. Ao longo da série, Mitsuri se destaca como uma das Caçadoras de Demônios mais carismáticas e populares, conhecida por sua força de vontade e sua capacidade de inspirar os outros. Ela forma laços estreitos com seus colegas de equipe e se torna uma figura de apoio e encorajamento para eles. No entanto, por trás de sua personalidade vibrante, Mitsuri também carrega uma dor profunda devido às tragédias que testemunhou em sua vida. Sua determinação em superar os desafios e proteger aqueles que ama a tornam uma personagem admirável e memorável na série.'
    },
    {obanai: 'Obanai Iguro', respiracao: 'Serpente',
        historia: 'Obanai Iguro Ele é apresentado como um dos membros mais talentosos e dedicados do Corpo de Caçadores de Demônios. A história de Obanai começa quando ele era jovem e sofreu uma tragédia pessoal, perdendo seus pais para um demônio. Determinado a vingar suas mortes e proteger outros inocentes, Obanai se torna um Caçador de Demônios e se dedica a combater as forças do mal. Ele é treinado na Respiração da Serpente, uma técnica de espada poderosa que ele domina com habilidade e destreza. Ao longo da série, Obanai é retratado como um indivíduo sério e determinado, cuja lealdade aos seus colegas de equipe e seu senso de dever são inabaláveis. Ele forma laços estreitos com outros Caçadores de Demônios e se torna um aliado confiável e respeitado. No entanto, por trás de sua fachada austera, Obanai também carrega um fardo emocional devido às tragédias que testemunhou em sua vida. Sua jornada é marcada por desafios difíceis e sacrifícios pessoais, mas sua determinação em proteger a humanidade dos demônios permanece inabalável. Obanai é uma figura inspiradora e admirável na série, cujo compromisso com a justiça e o dever o torna uma peça fundamental na luta contra o mal.'
    },
    {sanemi: 'Sanemi Shinazugawa', respiracao: 'Vento',
        historia: 'Sanemi Shinazugawa é introduzido como um dos Caçadores de Demônios mais poderosos e implacáveis do Corpo de Caçadores de Demônios. A história de Sanemi começa quando ele era jovem e testemunhou a morte de sua irmã mais nova por um demônio. Esse evento traumático moldou sua visão do mundo e o motivou a se tornar um Caçador de Demônios determinado a exterminar todos os demônios. Sanemi é conhecido por sua natureza hostil e sua relutância em confiar nos outros, mas ele é um guerreiro excepcionalmente habilidoso, treinado na Respiração do Vento. Ao longo da série, Sanemi enfrenta numerosos desafios e batalhas difíceis, demonstrando uma força de vontade e determinação inabaláveis. Ele forma laços complicados com seus colegas de equipe, especialmente com Tanjiro Kamado, e sua jornada é marcada por conflitos internos e crescimento pessoal. Apesar de sua fachada dura, Sanemi também carrega uma profunda dor e culpa por não ter sido capaz de proteger sua irmã. Sua jornada é uma busca constante por redenção e vingança, e sua determinação em proteger os inocentes e derrotar os demônios o torna uma figura respeitada e temida na série.'
    },
    {gyomei: 'Gyomei Himejima', respiracao: 'Pedra',
        historia: 'Sanemi Shinazugawa é introduzido como um dos Caçadores de Demônios mais poderosos e implacáveis do Corpo de Caçadores de Demônios. A história de Sanemi começa quando ele era jovem e testemunhou a morte de sua irmã mais nova por um demônio. Esse evento traumático moldou sua visão do mundo e o motivou a se tornar um Caçador de Demônios determinado a exterminar todos os demônios. Sanemi é conhecido por sua natureza hostil e sua relutância em confiar nos outros, mas ele é um guerreiro excepcionalmente habilidoso, treinado na Respiração do Vento. Ao longo da série, Sanemi enfrenta numerosos desafios e batalhas difíceis, demonstrando uma força de vontade e determinação inabaláveis. Ele forma laços complicados com seus colegas de equipe, especialmente com Tanjiro Kamado, e sua jornada é marcada por conflitos internos e crescimento pessoal. Apesar de sua fachada dura, Sanemi também carrega uma profunda dor e culpa por não ter sido capaz de proteger sua irmã. Sua jornada é uma busca constante por redenção e vingança, e sua determinação em proteger os inocentes e derrotar os demônios o torna uma figura respeitada e temida na série.'
    },
    {muichiro:'Muichiro Tokito', respiracao: 'Névoa',
        historia: 'Muichiro Tokito é introduzido como um Caçador de Demônios talentoso e habilidoso, conhecido por sua natureza calma e introspectiva. A história de Muichiro começa quando ele era jovem e testemunhou a morte de sua família por demônios. Essa tragédia o deixou traumatizado e sem memória de seu passado, levando-o a viver uma vida solitária e isolada. No entanto, Muichiro é encontrado por outros Caçadores de Demônios e é treinado para se tornar um guerreiro habilidoso na Respiração da Névoa. Ao longo da série, Muichiro enfrenta desafios pessoais e lutas internas enquanto luta para recuperar sua memória e encontrar um propósito em sua vida. Ele forma laços estreitos com seus colegas de equipe e desenvolve um profundo senso de camaradagem e lealdade. Sua jornada é uma busca constante por autoconhecimento e redenção, e sua determinação em proteger os inocentes e derrotar os demônios o torna uma figura respeitada e admirada na série. Muichiro é retratado como um exemplo de resiliência e força, capaz de superar grandes desafios e encontrar esperança mesmo nas circunstâncias mais sombrias.'
    },
    {tengen: 'Tengen Uzui', respiracao: 'Som',
        historia:'Tengen Uzui é apresentado como um dos Caçadores de Demônios mais habilidosos e extravagantes do Corpo de Caçadores de Demônios. A história de Tengen começa quando ele era jovem e se tornou um renomado espadachim após anos de treinamento árduo. Ele é conhecido por sua personalidade extrovertida e sua aparência chamativa, com cabelos longos e um estilo de vestimenta extravagante. Tengen é treinado na Respiração da Besta e é capaz de executar técnicas poderosas com sua espada. Ao longo da série, Tengen é retratado como um indivíduo confiante e destemido, sempre pronto para enfrentar desafios difíceis e proteger os inocentes. Ele forma laços estreitos com seus colegas de equipe e é admirado por sua habilidade de liderança e sua capacidade de inspirar outros. No entanto, por trás de sua fachada extravagante, Tengen também carrega um senso de responsabilidade e dever para com seus companheiros de equipe e para com a humanidade. Sua jornada é uma busca constante por excelência e justiça, e sua determinação em proteger os fracos e derrotar os demônios o torna uma figura respeitada e admirada na série. Tengen é uma fonte de inspiração para outros Caçadores de Demônios e uma força vital na luta contra as forças do mal.'
    },
]
const mainBackground = document.querySelector('.main')

getPersonagem.forEach((p)=>{
    p.addEventListener('click', (e)=>{
        const dataName = p.dataset.personagens
        mainBackground.style.backgroundImage = `url(../../dist/assets/personagens-background/${dataName}.jpg)`;
        personagensNomes.forEach((personagem)=>{ 
            if(personagem[dataName]){
                if(dataName == 'nezuko'){
                    selecionarNome.innerHTML = personagem[dataName]
                    categoria.innerText = 'TIPO: '
                    respiracao.innerHTML = personagem['tipo']
                }else{
                    categoria.innerText = 'RESPIRAÇÃO: '
                    selecionarNome.innerHTML = personagem[dataName]
                    respiracao.innerHTML =  personagem['respiracao']
                }
                personagemTitulo.innerHTML = personagem[dataName]
                personagemHistoria.innerHTML = personagem['historia']
            }
        })
    })
})